# Generated by Django 5.1.7 on 2025-06-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новое Произведение)', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание-Описание', max_length=250, verbose_name='Описание')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевод?')),
                ('author_original', models.CharField(default='Автор', max_length=250, verbose_name='Автор оригинала')),
                ('original', models.CharField(default='Название оригинала', max_length=250, verbose_name='Оригинал')),
                ('fandom', models.ManyToManyField(related_name='works', to='meta_data.fandom', verbose_name='Фандом')),
                ('genres', models.ManyToManyField(related_name='works', to='meta_data.genres', verbose_name='Жанры')),
                ('orientation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='meta_data.orientation', verbose_name='Направление')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='meta_data.rating', verbose_name='Рейтинг')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='meta_data.size', verbose_name='Размер')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='meta_data.status', verbose_name='Статус')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='meta_data.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='WorksQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='Ответ', max_length=250, verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_data.questions')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.works')),
            ],
            options={
                'verbose_name': 'Вопрос произведения',
                'verbose_name_plural': 'Вопросы произведения',
                'db_table': 'works_questions',
                'unique_together': {('work', 'question')},
            },
        ),
        migrations.AddField(
            model_name='works',
            name='questions',
            field=models.ManyToManyField(related_name='works', through='works.WorksQuestions', to='meta_data.questions', verbose_name='Вопросы'),
        ),
    ]
