# Generated by Django 5.1.7 on 2025-03-24 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ключ')),
                ('name', models.CharField(default='Новое Произведение)', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание-Описание', max_length=250, verbose_name='Описание')),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(verbose_name='Дата редактирования')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевод?')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'db_table': 'works',
            },
        ),
    ]
