# Generated by Django 5.1.7 on 2025-06-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая направленность произведения', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Основной акцент произведения заключается в ...', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направленность',
                'verbose_name_plural': 'Направленности',
                'db_table': 'orientation',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый размер произведения', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Кол-во страниц', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Размер произведения',
                'verbose_name_plural': 'Размеры произведения',
                'db_table': 'size',
            },
        ),
        migrations.AddField(
            model_name='works',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.orientation'),
        ),
        migrations.AddField(
            model_name='works',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.size'),
        ),
    ]
