# Generated by Django 5.1.7 on 2025-06-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(default='Новая глава', max_length=100, verbose_name='Название')),
                ('first_comment', models.CharField(default='', max_length=100, verbose_name='Примечание автора')),
                ('text', models.CharField(default='Текст главы', max_length=100, verbose_name='Текст')),
                ('end_comment', models.CharField(default='', max_length=100, verbose_name='Примечание автора')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='works.works', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'db_table': 'chapters',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
