# Generated by Django 5.1.7 on 2025-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_orientation_size_works_orientation_works_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый жанр', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание жанра', max_length=250, verbose_name='Описание')),
                ('mark', models.BooleanField(default=False, verbose_name='Жанр(0)/Тег(1)?')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Формулировка вопроса', max_length=100, verbose_name='Вопрос')),
                ('description', models.CharField(default='Пояснение (подробное раскрытие вопроса, возможно с примером)', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вопрос о произведении',
                'verbose_name_plural': 'Вопросы о произведении',
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='works',
            name='genres',
            field=models.ManyToManyField(related_name='works', to='works.genres'),
        ),
        migrations.CreateModel(
            name='WorksQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='Ответ', max_length=250, verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.questions')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.works')),
            ],
            options={
                'db_table': 'works_questions',
                'unique_together': {('work', 'question')},
            },
        ),
        migrations.AddField(
            model_name='works',
            name='questions',
            field=models.ManyToManyField(related_name='works', through='works.WorksQuestions', to='works.questions'),
        ),
    ]
