# Generated by Django 5.1.7 on 2025-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='end_comment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание автора'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='first_comment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание автора'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='text',
            field=models.TextField(default='Текст главы', verbose_name='Текст'),
        ),
    ]
