# Generated by Django 5.1.7 on 2025-06-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_genres_questions_works_genres_worksquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название фандома', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фандом',
                'verbose_name_plural': 'Фандомы',
                'db_table': 'fandom',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Сокращённое обозначение рейтинга', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Пояснение', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рейтинг по возрасту',
                'verbose_name_plural': 'Рейтинги по возрасту',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название статуса', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус работы',
                'verbose_name_plural': 'Статусы работ',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название типа', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'db_table': 'type',
            },
        ),
        migrations.AlterModelOptions(
            name='worksquestions',
            options={'verbose_name': 'Вопрос произведения', 'verbose_name_plural': 'Вопросы произведения'},
        ),
        migrations.AddField(
            model_name='works',
            name='fandom',
            field=models.ManyToManyField(related_name='works', to='works.fandom'),
        ),
        migrations.AddField(
            model_name='works',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.rating'),
        ),
        migrations.AddField(
            model_name='works',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.status'),
        ),
        migrations.AddField(
            model_name='works',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.type'),
        ),
    ]
