# Generated by Django 5.1.7 on 2025-06-15 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_chapters_end_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='end_comment',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Примечание автора'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='first_comment',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Примечание автора'),
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='author', max_length=100, verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_authors', to='works.works')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'works_authors',
                'unique_together': {('user', 'work')},
            },
        ),
        migrations.AddField(
            model_name='works',
            name='authors',
            field=models.ManyToManyField(related_name='works_authors', through='works.Authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(blank=True, null=True, verbose_name='Оценка произведения')),
                ('readed', models.BooleanField(default=False, verbose_name='Отметка Прочитано')),
                ('data_of_readed', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_readers', to='works.works')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'db_table': 'works_readers',
                'unique_together': {('user', 'work')},
            },
        ),
        migrations.AddField(
            model_name='works',
            name='readers',
            field=models.ManyToManyField(related_name='works_readers', through='works.Readers', to=settings.AUTH_USER_MODEL, verbose_name='Читатели'),
        ),
    ]
