# Generated by Django 5.1.7 on 2025-06-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_chapters_end_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='works',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='role',
            field=models.CharField(default='soauthor', max_length=100, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_authors', to='works.works'),
        ),
    ]
