version: '3.8'

services:
  frontend:
    build:
      context: ../prolog_vue
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prolog-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - prolog-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - prolog-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  prolog-network:
    driver: bridge