# Generated by Django 5.1.7 on 2025-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название фандома', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фандом',
                'verbose_name_plural': 'Фандомы',
                'db_table': 'fandom',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый жанр', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Описание жанра', max_length=250, verbose_name='Описание')),
                ('mark', models.BooleanField(default=False, verbose_name='Жанр(0)/Тег(1)?')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая направленность произведения', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Основной акцент произведения заключается в ...', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направленность',
                'verbose_name_plural': 'Направленности',
                'db_table': 'orientation',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Формулировка вопроса', max_length=100, verbose_name='Вопрос')),
                ('description', models.CharField(default='Пояснение (подробное раскрытие вопроса, возможно с примером)', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вопрос о произведении',
                'verbose_name_plural': 'Вопросы о произведении',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Сокращённое обозначение рейтинга', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Пояснение', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рейтинг по возрасту',
                'verbose_name_plural': 'Рейтинги по возрасту',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый размер произведения', max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='Кол-во страниц', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Размер произведения',
                'verbose_name_plural': 'Размеры произведения',
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название статуса', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус работы',
                'verbose_name_plural': 'Статусы работ',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название типа', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'db_table': 'type',
            },
        ),
    ]
